name: Create envfile

on: [ push ]

jobs:

  count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Count themes
        run: |
          THEMES_NUMBER=$(ls ./themes/ | wc -l)
          echo "Themes counted: $THEMES_NUMBER"
          echo "THEMES_NUMBER=$THEMES_NUMBER" >> $GITHUB_ENV
      - name: Export one variable
        uses: UnlyEd/github-action-store-variable@v2.1.0
        with:
          variables: THEMES_NUMBER="$THEMES_NUMBER"

  create-envfile:
    needs: count
    runs-on: ubuntu-latest
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_THEMES_NUMBER: ${{ vars.THEMES_NUMBER }}
        file_name: .env
        fail_on_empty: true
        sort_keys: false
